### ISSUE TITLE
Time column in exported log

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#155]
How do I interpret the time column in the log?

![log](https://user-images.githubusercontent.com/7985331/85230571-002e2f00-b3e9-11ea-870d-766d9fef4ea5.png)

**Comment by rlankhorst** [comment]
Hi @ajtruckle, 

Sorry, missed your post. I'll have to keep a closer watch here :)

This is the UNIX timestamp, which is the time in seconds since 1970. In the latest version I've also added a "nice time" column, with a human readable time format. 

Rogier
