### ISSUE TITLE
Date formatting

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#156]
The shortdates are not showing in UK format for some reason?

![dates](https://user-images.githubusercontent.com/7985331/85230607-379cdb80-b3e9-11ea-9957-e6197a267274.png)

As per my other feedback, I propose new choices:

- This year
- All

In addition, for where you want more than a month, it is easier if the two calendars were separated o you can set start / end dates.

**Comment by AertHulsebos** [comment]
I can't reproduce the issue. Do you have the date format correct in your WordPess settings? We will have a look at the rest for a following update. regards Aert

Thanks a lot!

**Comment by ajtruckle** [comment]
> Do you have the date format correct in your WordPess settings?

Yes, the date settings are correct:

![dates](https://user-images.githubusercontent.com/7985331/85268810-ecc5a700-b46e-11ea-820c-27c790515a44.png)
