### ISSUE TITLE
Observations about WP Search Insights

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#179]
Hi

Yesterday I added **color picker** to my list of filters:

![Insight1](https://user-images.githubusercontent.com/7985331/100343127-dfd95080-2fd6-11eb-8e29-37a85ffe6994.png)

Yet, when I look through my website I still see references to the term:

![Insight2](https://user-images.githubusercontent.com/7985331/100343193-f8496b00-2fd6-11eb-86d2-1220a055d37f.png)

![Inisight4](https://user-images.githubusercontent.com/7985331/100343235-04352d00-2fd7-11eb-9b44-d4a3c0f7c15f.png)

### Tooltips

Is it possible to introduce tooltips? Some search terms are longer than the column will display unless I look down at the status bar:

![Insight3](https://user-images.githubusercontent.com/7985331/100343371-2f1f8100-2fd7-11eb-84d1-5599427a9aff.png)

See?

Thanks for your consideration of these issues.

**Comment by rlankhorst** [comment]
Hi @ajtruckle, thanks for your input. I'll run some tests on the filter. The tooltip suggestion is a good one as well, I've added it to our to do list.

**Comment by ajtruckle** [comment]
Hi

I don't know if you have looked at this because I have the latest version of your plugin.

I still continue to have their search records which I can only conclude are spam.

Even though I types it in the filter it is not working.

![Search2](https://user-images.githubusercontent.com/7985331/105611058-10f1b980-5dab-11eb-82a5-7ce59e69ca38.jpg)
![Search](https://user-images.githubusercontent.com/7985331/105611059-118a5000-5dab-11eb-946f-386aac1b2131.jpg)
![Search4](https://user-images.githubusercontent.com/7985331/105611060-1222e680-5dab-11eb-9867-5728a0d75c7e.jpg)
![Search3](https://user-images.githubusercontent.com/7985331/105611061-1222e680-5dab-11eb-9716-229ed316f5a3.jpg)

As a possible easier and better user experience can you please offer us to filter out a search term directly from the dashboard widget? Maybe a icon to add to filter. And then, to make sure it does truly purge it from everywhere.

The figures for search results on by site and not really truly because of the odd search terms like "color picker" and "">".

Please reply, as I had allowed some 2 months. :)

Hope you are all well.

**Comment by mwolters90** [comment]
Hi @ajtruckle,

we haven't looked into this yet, thanks for bringing it to our attention. I will look into the filter functionality later this week.

**Comment by Mark-met-een-K** [comment]
@ajtruckle I've added a secondary button to the 'All Searches' table on the Search Insights settings page, called ignore selected. Selecting an entry in the table and pressing the ignore selected will remove the result from all database tables, add it to the filtered terms and clears the cache of each overview, including the dashboard widget. This allows you to easily remove results from the search results and prevent them from ever cluttering your results again.  The delete selected button will remove a single row from the table and update the count accordingly. I'll look at adding tooltips to these buttons to clarify the difference.

I've also tested the filter functionality and didn't encounter any issues. Could you try if removing the color picker entry from the filter setting, and ignoring the color picker result via the ignore selected button resolves the issue? You can find these changes on this branch: https://github.com/Mark-met-een-K/wp-search-insights/tree/1.3.7

If you still experience any filter issues, could you create a temporary account and drop me an e-mail or fill out the contact form on https://wpsearchinsights.com/ so I can troubleshoot the issue?

Let me know if you have any other questions and/or suggestions.

**Comment by ajtruckle** [comment]
Hi! 

Thanks for the upgrades which I have just tried. Good progress"

I have two observations at the moment.

1. It might be an idea to throw up a popup message box asking the user to confirm they want to ignore it since it is undoable and they might do it by mistake.

2. For some reason when I try to "ignore the highlighted entry it only takes out that row. All the other rows still show:

![IgnoreSelected](https://user-images.githubusercontent.com/7985331/106380431-14d49b80-63aa-11eb-974c-36eb477f5611.jpg)

**Comment by ajtruckle** [comment]
Update. Even though it did not remove the `" > ` items when I asked it to, it seems that when I revisited teh dashbord that they have actually been removed. I can't see them now.

**Comment by ajtruckle** [comment]
It is working very well!

Only thing I noticed so far:

![Results](https://user-images.githubusercontent.com/7985331/106740608-8b73d200-6612-11eb-9af6-b834e5d07304.jpg)

For some reason it shows a double entry?

**Comment by Mark-met-een-K** [comment]
@ajtruckle glad to hear the feature is working well. The ignore button will remove all rows containing that result, although the table only removes one row visibly. Reloading the page will show the update table. I will gradually improve the feature with your suggestions, like removing all rows after ignoring a result and adding an explanation about what the button does exactly. 

The plugin won't track the same search term when it's made within 10 seconds of the previous search. It's possible these searches have been made more than 10 seconds apart, thus the plugin is tracked them both.

**Comment by ajtruckle** [comment]
Understood! Well done. Works great. 😀
