### ISSUE TITLE
Any new version on the horizon?

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#180]
Thanks.

**Comment by ajtruckle** [comment]
Bump

I see now the server is not found:

https://wpsearchinsights.com/#faq

What is the situation friends?

**Comment by Mark-met-een-K** [comment]
Hi @ajtruckle,

thanks for attending me to the website not working. I'll get on it. In regards to plugin support, the plugin is still supported, however I'm not actively developing it currently as you have noticed. However, it is tested with new WP versions etc so it will definitely continue to work as is.

Let me know if you have any other questions.

**Comment by ajtruckle** [comment]
Ok. That is good. It is just that peoples questions don’t get answers in the wp forum from what I can see, which gives a bad impression and inactivity can lead to plug-in closures as you know. Maybe add a status on the plug-in site?

I appreciate you answering me here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
Hi

This issue is not resolved and now it deriects to various websites. It is not good. This happens when I click the **Documentation** button. WHats happening? Thank you.

**Comment by Mark-met-een-K** [comment]
Hi @ajtruckle, 

the URL has been updated to wpsi.io. The latest update 1.3.7 contains updated links.

**Comment by ajtruckle** [comment]
Thanks!

When with 1.3.7 be released?

Andrew

________________________________

**Comment by Mark-met-een-K** [comment]
1.3.7 was released a little over a month ago. There should be an update available in your WordPress dashboard. Could you check if that's the case?

**Comment by Mark-met-een-K** [comment]
I just remembered you are likely using a slightly modified version of the plugin from this thread: https://github.com/Mark-met-een-K/wp-search-insights/issues/179#issuecomment-772519753. Coincidentally this branch also has version number 1.3.7 which is likely why the update with new links didn't appear in your WP updates menu. I have now updated the links in that branch as well so you can continue using that feature: https://github.com/Mark-met-een-K/wp-search-insights/tree/1.3.7

**Comment by ajtruckle** [comment]
Or could you do a 1.3.8 or something so I can just do a check for update instead of a manually download / install of zip?

**Comment by ajtruckle** [comment]
Awesome. Thanks!
________________________________
