### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#189]
Hi

If I visit my forum:

https://www.publictalksoftware.co.uk/support-forums/

And, if I search using the bar on the left "closing prayer" it shows entries OK.

But, if i try the search bar above the support forum I get a critical error. And it says it is concerning WP Search Insights.

**Comment by ajtruckle** [comment]
If I put `DEBUG` mode on it says:

```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/wp-search-insights/integrations/bbpress.php:14 Stack trace: 
#0 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/class-wp-hook.php(308): wpsi_track_bbpress(true, Object(WP_Query)) 
#1 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/plugin.php(205): WP_Hook->apply_filters(true, Array) 
#2 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/search/template.php(113): apply_filters('bbp_has_search_...', true, Object(WP_Query)) 
#3 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/gd-power-search-for-bbpress/core/objects/bbpress.php(83): bbp_has_search_results() 
#4 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/class-wp-hook.php(308): gdpos_core_bbpress->search_force_form('') 
#5 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#6 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#7 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/templates/default/bbpress/content-search.php(21): do_action('bbp_template_be...') 
#8 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/template.php(785): require('/customers/e/9/...') 
#9 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/core/template-functions.php(103): load_template('/customers/e/9/...', false) 
#10 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/core/template-functions.php(41): bbp_locate_template(Array, true, false) 
#11 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/common/shortcodes.php(691): bbp_get_template_part('content', 'search') 
#12 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/core/theme-compat.php(773): BBP_Shortcodes->display_search(Array) 
#13 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/class-wp-hook.php(308): bbp_template_include_theme_compat('/customers/e/9/...') 
#14 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/plugin.php(205): WP_Hook->apply_filters('/customers/e/9/...', Array) 
#15 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/bbpress/includes/core/sub-actions.php(477): apply_filters('bbp_template_in...', '/customers/e/9/...') 
#16 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/class-wp-hook.php(308): bbp_template_include('/customers/e/9/...') 
#17 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/plugin.php(205): WP_Hook->apply_filters('/customers/e/9/...', Array) 
#18 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-includes/template-loader.php(104): apply_filters('template_includ...', '/customers/e/9/...') 
#19 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-blog-header.php(19): require_once('/customers/e/9/...') 
#20 /customers/e/9/c/publictalksoftware.co.uk/httpd.www/index.php(17): require('/customers/e/9/...') 
#21 {main} thrown in /customers/e/9/c/publictalksoftware.co.uk/httpd.www/wp-content/plugins/wp-search-insights/integrations/bbpress.php on line 14
```

Please help. Thanks!

**Comment by Mark-met-een-K** [comment]
Hi @ajtruckle,

thank you for reporting this issue. There seems to be an issue with tracking searches with results in the BBPress integration. This has been fixed in this branch: https://github.com/Mark-met-een-K/wp-search-insights/tree/bbpress-integration-fix. Replacing your current integrations/bbpress.php with the one from that branch will solve the issue. This will be included in the next update.

**Comment by ajtruckle** [comment]
Hi

Now my site seems messed up :(

Please view my site ASAP. Thanks.

**Comment by ajtruckle** [comment]
I have had to rename the search insights folder because it was breaking my site completely.

**Comment by ajtruckle** [comment]
For some reason, when I used the new bbpress source code file I had the top half of the screen showing the github page. It was most peculiar. The site became inoperable so I renamed the plugin folder to deactivate the plugin and let me use the site again.

**Comment by Mark-met-een-K** [comment]
Sounds like there might be some HTML copied with the new integration. Could you verify the integrations/bbpress.php file contains just this code and nothing else:

`<?php
defined('ABSPATH') or die("you do not have access to this page!");

/**
 * Process BBPress searches
 * @param $posts
 * @param $query
 *
 * @return mixed
 */

function wpsi_track_bbpress( $posts, $query ) {

    if ( is_array( $query->posts ) ) {
        $result_count = count( $query->posts );
    } else {
        $result_count = 0;
    }

	if (isset($query->query_vars['s'])){
		$search_terms = $query->query_vars['s'];
		WPSI::$search->process_search_term( $search_terms , $result_count, 'bbpress');
	}

	return $posts;
}
add_filter( 'bbp_has_search_results', 'wpsi_track_bbpress', 10, 2);`

**Comment by ajtruckle** [comment]
That was it. My mistake was right-clicking the php file and selecting Save As.

This time I went to the Raw view and copied the correct data.

All good.
