### ISSUE TITLE
Layout of controls in the dash board

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#75]
Thanks for version 1.2 and i appreciate it is at beta stage.

One initial observation is the layout of the controls for **All Searches**:

![Issue](https://user-images.githubusercontent.com/7985331/76321563-1e5c9d00-62da-11ea-8c62-9aa52be1cdff.png)

The page navigation bar is overlapping items in the table. See?

**Comment by ajtruckle** [comment]
Just to clarify, on page 1 the navigation bar is under the table:

![Update](https://user-images.githubusercontent.com/7985331/76365583-84b7de80-631f-11ea-9a89-0dfbbefae065.png)

When you click on page 2 etc. the issue appears.

**Comment by ajtruckle** [comment]
Just checking you have received this issue I raised?

Thanks.

**Comment by AertHulsebos** [comment]
Yes we did! Working at it as we speak:)

**Comment by ajtruckle** [comment]
This seems better now (certainly on my PC and iPad). Thanks.

**Comment by ajtruckle** [comment]
Sorry to be a pain. With the latest update, on my iPad in landscape:

![F5BB861B-D837-4CEE-AE13-1316CD92D72A](https://user-images.githubusercontent.com/7985331/77613769-6e1aa580-6f23-11ea-8082-16f4ddd73f28.jpeg)

Minor overlap issue. Sorry!

**Comment by rlankhorst** [comment]
@ajtruckle The new update contains several fixes for mobile, which should resolve the issue.
