### ISSUE TITLE
Layout of controls / responsiveness on iPhone

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#76]
I am also finding it hard to use the **All Searches** panel on a iPhone. It suffers from the same pagination bar overlap problem but when I start to drag it aroudn to have a look it ends up freezing and stops responding:

![File 10-03-2020, 14 24 09](https://user-images.githubusercontent.com/7985331/76322456-557f7e00-62db-11ea-919d-da7bfe751930.jpeg)

**Comment by ajtruckle** [comment]
Just checking you have received this issue I raised?

Thanks.

**Comment by ajtruckle** [comment]
This is working better on my iPad. Landscape is best. Portrait the width is too wide but atleast I think I can navigate it.

But the iPhone is still not Ok. If i try to drag the display it just freezes. I think you need to have a different layout style for the data for smaller screens to avoid this.

**Comment by ajtruckle** [comment]
These are screen shots on iPhone (version 1.2).

OK:

![Photo 31-03-2020, 11 36 45](https://user-images.githubusercontent.com/7985331/78018129-3ce80e00-7345-11ea-8ff5-7be8929cdcae.png)

OK:

![Photo 31-03-2020, 11 37 01](https://user-images.githubusercontent.com/7985331/78018130-3e193b00-7345-11ea-9774-1bbb9714c5b2.png)

OK:

![Photo 31-03-2020, 11 37 25](https://user-images.githubusercontent.com/7985331/78018132-3eb1d180-7345-11ea-9499-c03925a461ab.png)

Not OK:
![Photo 31-03-2020, 11 37 40](https://user-images.githubusercontent.com/7985331/78018134-3eb1d180-7345-11ea-9129-63758cc63b0f.png)

This latter area is OK on a iPad in portrait and landscape views. But iPhone is not OK. It needs to be displayed different. As an example, try to view the "Users List" from the WordPress Admin panel and try it on a iPhone. The user data is presented differently so that it is still useable.

**Comment by rlankhorst** [comment]
@ajtruckle although it's difficult to get it properly on mobile, I think we've  managed to get most info.
