### ISSUE TITLE
All Searches Sort Order

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#77]
Thanks for fixing the issues with sorting the records by date. :)

It would be nice if the chosen sort setting is retained. At the moment it reverts to default sorting. Is this possible?

Also, may I ask about **SearchResult.aspx**. What exactky is that as it has no starting page:

![Update](https://user-images.githubusercontent.com/7985331/76365734-fc860900-631f-11ea-8dd8-174f57504c3d.png)

**Comment by ajtruckle** [comment]
Just checking you have received this issue I raised?

Thanks.

**Comment by rlankhorst** [comment]
Hi @ajtruckle, 

Thanks for your input! We're working on resolve the issues. 

Retaing the sort order is something we will implement in the next version, I've added it to our to do list.

**Comment by rlankhorst** [comment]
@ajtruckle, this is currently implemented
