### ISSUE TITLE
Adverts in dashboard

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#83]
I am using your latest beta (from yesterday).

I noticed this in my dashboard:

![DashboardSSL](https://user-images.githubusercontent.com/7985331/77150624-32e42680-6a8c-11ea-9950-923367ee645c.png)

I already have this plugin installed. Is it not possible for your plugin to detect if it is installed and suppress the advert?

**Comment by rlankhorst** [comment]
Hi @ajtruckle, a good idea, we'll put it on our list! Thanks for all your input. It's really valuable for us!

**Comment by rlankhorst** [comment]
@ajtruckle the latest version adjusts for installed versions of the plugins.
