### ISSUE TITLE
Backend issue on iPad 

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#90]
Please see:

![4EFA8376-8CCC-412F-9BBD-C1C3BE738A75](https://user-images.githubusercontent.com/7985331/77537605-48938a80-6e96-11ea-97a9-c951f8cab760.png)

Basically, if I put my finger in the white space and drag it drags the history list. But then it freezes in that spot and can’t be put back.

I think that on small devices the history grid shouldn’t move if I accidentally drag it.

**Comment by AertHulsebos** [comment]
Hi @ajtruckle,

Please check the current master, it shouldn't happen anymore on touch devices.

Aert

**Comment by ajtruckle** [comment]
> Hi @ajtruckle,
> 
> Please check the current master, it shouldn't happen anymore on touch devices.
> 
> Aert

That is working great! Thanks! Only thing I notice now is the **View** button:

![2B3ED998-9C97-4690-9A49-17E29CB5663B](https://user-images.githubusercontent.com/7985331/77545266-18ea7f80-6ea2-11ea-8dde-3a15ae052c45.jpeg)

Overlaps border.

**Comment by AertHulsebos** [comment]
Ah. Thanks. Will have a look

**Comment by AertHulsebos** [comment]
This should be fixed.

**Comment by ajtruckle** [comment]
Thank you.
