### ISSUE TITLE
Possible typo — "The Search Filter" Help Topic

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#92]
Please look [here](https://wpsearchinsights.com/the-search-filter/). Quote:

> https://wpsearchinsights.com & https://wpsearchinsights.com should be added both, as they are not the same. This is true for spelling mistakes as well.

The above text is confusing because:

- https://wpsearchinsights.com
- https://wpsearchinsights.com

The links **are** both the same. Yet your documentation states they are "not the same". I assume there is a typo somewhere.

**Comment by AertHulsebos** [comment]
Hi. The spelling mistake wasn't in the post, just in the output. I can't seem to add a http:// address as plain text without the output changing it to https://. I don't know how yet, but making it cursive helps. Funny, at least.

https://wpsearchinsights.com/the-search-filter/

Thanks!
