### ISSUE TITLE
The dashboard filter drop-down

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#93]
In the backend we can choose from:

* Day
* Week
* Month

But it is not remembering our choices. When we go back to the page it reverts to Week.

Is it possible to at-least allow us to set a default filter choice in the settings? Else remember the choices we last used?

**Comment by mwolters90** [comment]
Hi Andrew,

yes, we will implement this feature and let you know once it's done.

Mark

**Comment by ajtruckle** [comment]
Thanks.

**Comment by rlankhorst** [comment]
@ajtruckle we've changed the selector to a date range selector, the state will be remembered.

**Comment by ajtruckle** [comment]
Thanks. When will this latest version be available in WordPress Updates?

**Comment by rlankhorst** [comment]
We're currently wrapping up testing, and have planned to release it on Tuesday.
