### ISSUE TITLE
Using Ivory Search Plugin

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#97]
Hi !

I stumbled on "Ivory Search" plugin. I still have the "Power Search Plugin" that users can use directly on the bbPress forum.

But, "Ivory Search" is designed to replace the standard "Search" form in my sidebar. See:

https://www.publictalksoftware.co.uk

What is great is that I have configured this search feature to search bbpress topics and downloads! Cool.

Say for example you search for "zoom" it will display some forum and website posts.

But when I go to my search dashboard the search entry is not logged. Even though I have the "log admin search" enabled.

Please advise. Thanks.

**Comment by mwolters90** [comment]
Hi Andrew,

we will test the plugin with Ivory Search to see why it's not working correctly.

Mark

**Comment by ajtruckle** [comment]
Thanks. This is my priority now as I am not getting much search content detected now.

**Comment by ajtruckle** [comment]
[Here](https://ivorysearch.com/topic/styling-search-edit-box-for-ipad/#post-4397) the author of Ivory Search says:

> It should work as the Ivory Search plugin uses default WordPress search functionality.

![Results](https://user-images.githubusercontent.com/7985331/80005624-bf369e80-84bb-11ea-979e-3d2bd3044b67.png)

As you can see, I have not had any results for 2 days.

**Comment by ajtruckle** [comment]
I think this is OK. Sorry for confusion. I thought I had switched on the admin option to log searches. Now that I have I can see content.

Clearly no one has used the search I guess!

**Comment by rlankhorst** [comment]
Ok, great! I’ll close this issue then.
