### ISSUE TITLE
I think I have found a bug

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#98]
This is a valid post on my site:

https://www.publictalksoftware.co.uk/2019/03/25/customising-the-worksheet/

I noticed this in the Search Dashboard I had this entry:

![Search](https://user-images.githubusercontent.com/7985331/80522748-f823b700-8984-11ea-90a9-a476b7d31788.png)

When I clicked the link it was failing with a 404. But then I realised that the actual link was different:

https://www.publictalksoftware.co.uk/2019-03-25-customising-the-worksheet

See the different? 

- 2019/03/25/
- 2019-03-25-

As a result I get 404 for some links.

**Comment by ajtruckle** [comment]
The other slight difference was that the master URL has a trailing `/` but the linked to post does not.

**Comment by rlankhorst** [comment]
@ajtruckle this is fixed in the current version
