### ISSUE TITLE
Exporting to CSV

### ISSUE THREAD

**Issue by ajtruckle** [Mark-met-een-K/wp-search-insights#99]
I am using the latest beta with fix for the urls.

In the dashboard I can see the "Download to CSV" when the default WEEK is selected.

If I choose "DAY" or "MONTH" the"Download to CSV" option vanishes. And, if I hit F5 it reverts to "WEEK".

So why can't I download the CSV for all three of these settings?

**Comment by rlankhorst** [comment]
@ajtruckle the current git version contains a new export method, which allows to export by any chosen data range directly from the back-end (as opposed to the current version, which downloaded the selection on screen).
